### PR TITLE
Fix: formatting

### LINKED ISSUE #6: Formatting & linting errors
Some of the files have a mix of tabs and spaces used for their indentation, and some of the indentation in the python scripts is inconsistent. This causes my IDE to flare up with a bajillion warnings when editing the files, so I'd like to clean them up for my own sanity.

It's an easy fix, and would make me less nervous about incurring "large" changes for relatively small commits in the future. What do you think?

### PR DESCRIPTION
**Pull request by EdwardSimmons**
For the `.f90` files, all I've really changed is indentation.

For the `.py` files, I've fixed indentation and changed some variable names + imports to adhere to PEP8 standards.

I renamed `analysisV2.py` to `analysis.py` partly for naming convention, partly because there is no `V1`.

### CODE REVIEW

File: itg.f90 [hunk 1]
```diff
@@ -102,207 +101,207 @@ PROGRAM itg
...
 ! Writing initial conditions to file !
 ! ---------------------------------- !
 
-  IF (MyRank.EQ.0) THEN
+   IF (MyRank.EQ.0) THEN
 
-	OPEN (5,FILE=TRIM(runpath)//'/parameters.txt')
-	WRITE (5,*) NumSteps,dt,length,NumModes,InitialMode,FinalMode,tau
-	CLOSE (5)
-	OPEN (5,FILE=TRIM(runpath)//'/xx.dat',FORM='unformatted',ACCESS='stream')
```
Comment (arkabokshi) [inline itg.f90:123]: I think your new changes have overwritten the previous merge to fix this issue.  It is `xx.dat` at a couple of places and `xx.txt` at two other places...

File: itg.f90 [hunk 2]
```diff
@@ -119,8 +119,8 @@ PROGRAM itg
         OPEN (5,FILE=TRIM(runpath)//'/parameters.txt')
         WRITE (5,*) NumSteps,dt,length,NumModes,InitialMode,FinalMode,tau
         CLOSE (5)
-        OPEN (5,FILE=TRIM(runpath)//'/xx.txt')
-        WRITE (5, *) xx
+        OPEN (5,FILE=TRIM(runpath)//'/xxdat',FORM='unformatted',ACCESS='stream')
```
Comment (arkabokshi) [inline itg.f90]: Dot missing in `xx.dat` ?

**Review by arkabokshi — APPROVED** [review]
